name: Bug report
description: Report a bug on the website.
title: "bug: "
labels: [bug]
body:
  - type: markdown 
    attributes:
      value: |
        **Thanks for helping improve the Elden Ring Cheat Sheet!**
        Please fill out the form below.

        **Note:** A bug can be as simple as an incorrect link.
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: How did you trigger this bug?
      value: |
        1. 
        2. 
        3. 
      render: bash
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A short description of what you expected to happen.
      placeholder: Describe what you expected to happen...
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you experiencing the issue on?
      multiple: true
      options:
        - Chrome
        - Edge
        - Firefox
        - Safari
