name: Feature request
description: Suggest an idea for this project.
title: "feature: "
labels: [enhancement]
body:
  - type: markdown 
    attributes:
      value: |
        **Thanks for helping improve the Elden Ring Cheat Sheet!**
        Please fill out the form below to request a feature.

        **Note:** A feature can be any enhancement to the website.
  - type: textarea
    attributes:
      label: Is your feature related to a problem?
      description: A short description of what the problem is.
      placeholder: Describe if the feature you're requesting is a fix to a problem or annoyance you're experiencing...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of your feature.
      placeholder: Describe your feature...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives you've considered
      description: A short description of any alternative solutions you've considered.
      placeholder: Describe any alternatives solutions you've considered...
