name: Missing item/content
description: Report missing items or content.
title: "missing: "
labels: [missing]
body:
  - type: markdown 
    attributes:
      value: |
        **Thanks for helping improve the Elden Ring Cheat Sheet!**
        Please fill out the form below.
  - type: dropdown
    attributes:
      label: Which sheet does this relate to?
      options:
        - Resources
        - Walkthrough
        - NPC Walkthrough
        - Questlines
        - Merchants
        - Bosses
        - Achievements
        - Armaments
        - Armor
        - Ashes
        - Spells
        - Key Items
        - Miscellaneous
        - New Game+
      multiple: true
    validations:
      required: true
  - type: input
    attributes:
      label: Which section is the content missing from?
      description: Name one or multiple sections.
      placeholder: E.g. Limgrave, Stormveil Castle...
    validations:
      required: true
  - type: textarea
    attributes:
      label: What's missing?
      description: A short description of what's missing.
      placeholder: Describe what's missing...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the location (if applicable)
      description: A short description of the location.
      placeholder: Describe the location of what's missing...
